[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200





  [[redirects]]
  from = "/contact"
  to = "https://myservermail.vercel.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
